# Generated by Django 4.2.3 on 2023-08-22 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0003_alter_vendor_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='categories',
            new_name='Category',
        ),
    ]
