# Generated by Django 4.2.3 on 2023-08-23 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0004_rename_categories_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
