# Generated by Django 4.2.3 on 2023-08-26 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0009_alter_vendor_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryOnly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_only', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='superadmin.category')),
            ],
        ),
    ]
