# Generated by Django 4.2.3 on 2023-08-27 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0010_categoryonly'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catgeory_only',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_only', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='superadmin.category')),
            ],
        ),
        migrations.DeleteModel(
            name='CategoryOnly',
        ),
    ]
