# Generated by Django 4.2.3 on 2023-08-29 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0011_catgeory_only_delete_categoryonly'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Catgeory_only',
        ),
    ]
